name: ci cd nnn

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.1'
    - name: Install dependencies
      run: pip install -r packages.yaml
    - name: Run tests
      run: python -m unittest discover tests
    


