name: ci cd nnn

on:
  push:
    branches: ["main"]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Dir
      run: cd ./api_revendeur
      
    - name: Setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.1'
    - name: Install dependencies
      run: |
       python -m pip install --upgrade pip
       pip install -r api_revendeur/packages.yaml
    - name: Run tests
      run: |
       pip install pytest
       pytest api_revendeur/tests/test_app.py
        
  analyze:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Sonarqube
      uses: sonarsource/setup-sonarqube@v1
      with:
        url: ${{ env.SONAR_URL }}
        token: ${{ secrets.SONAR_LOGIN }}
    - name: Analyze code
      run: |
        sonar-scanner 
          -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
          -Dsonar.sources=.
          -Dsonar.host.url=${{ env.SONAR_URL }}


